server:
  port: 9091

spring:
  application:
    name: service-consumer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-consumer?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

feign:
  client:
    config:
      # service-provider对应的是指定服务（可以大写，也可以小写）；注：此处的名字要与@FeignClient的value值保持一直
      SERVICE-PROVIDER:
#      service-provider:
        connect-timeout: 5000
        read-timeout: 5000
  # openfeign中自带Hystrix，配置启用hystrix
  hystrix:
    enabled: true
  # 配置对应的日志级别
#        loggerLevel: FULL
      # default对应的是所有服务
#      default:
#        connect-timeout: 5000
#        read-timeout: 5000
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/, http://localhost:9999/eureka/

# 配置以什么级别监控哪个接口，不能使用default来表示所有
logging:
  level:
    org.example.service.UserFeignClient: debug