server:
  port: 9090

spring:
  application:
    name: service-consumer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-consumer?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/, http://localhost:9999/eureka/